# Site settings
title: ShipOS
email: geir@shipos.org
description: The edge Operating System for ships
baseurl: ""
url: ""
download_button_url: ""

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
twitter_url:  

# Build settings
markdown: kramdown
